apply plugin: 'com.android.application'

android {
    namespace "com.sovereign.tools"
    compileSdk rootProject.hasProperty('compileSdkVersion') ? rootProject.getExtensionValue('compileSdkVersion') : 34

    defaultConfig {
        applicationId "com.sovereign.tools"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.webkit:webkit:1.9.0"
    implementation 'info.guardianproject:tor-android:0.4.7.8.1'
    implementation project(':capacitor-android')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation('androidx.test.ext:junit:1.1.5')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.5.1')
}
